version: "3"
services:
  moweb_back:
    build:
      context: ./moweb_back
    container_name: moweb_back
    ports:
      - 8080:8080
    volumes:
      - ./images:/images:rw
    environment:
      - db.url=${db_url}
      - db.username=${db_username}
      - db.password=${db_password}
      - db.dbname=${db_dbname}
      - hosturl=${hosturl}
    network_mode: "host"
  moweb_front:
    build:
      context: ./moweb_front
    container_name: moweb_front
    ports:
      - 8000:80
    environment:
      - VUE_MOWEB_API_URL=${VUE_MOWEB_API_URL}
      - VUE_ROOT_URL=${VUE_ROOT_URL}
      - VUE_OPENVIDU_SERVER_URL=${VUE_OPENVIDU_SERVER_URL}
      - VUE_KAKAO_API_KEY=${VUE_KAKAO_API_KEY}
      - OPENVIDU_SERVER_SECRET=${OPENVIDU_SERVER_SECRET}
