version: "3"
services:
  moweb_back:
    build:
      context: ./moweb_back
    container_name: moweb_back
    ports:
      - 8080:8080
    volumes:
      - ./images:/images:rw
    environment:
      - db.url=${db_url}
      - db.username=${db_username}
      - db.password=${db_password}
      - db.dbname=${db_dbname}
      - hosturl=${hosturl}
    network_mode: "host"
  moweb_front:
    build:
      context: ./moweb_front
    container_name: moweb_front
    ports:
      - 8000:80
    environment:
      - VUE_APP_MOWEB_API_URL=${VUE_APP_MOWEB_API_URL}
      - VUE_APP_ROOT_URL=${VUE_APP_ROOT_URL}
      - VUE_APP_OPENVIDU_SERVER_SECRET=${VUE_APP_OPENVIDU_SERVER_SECRET}
      - VUE_APP_KAKAO_API_KEY=${VUE_APP_KAKAO_API_KEY}
      - VUE_APP_OPENVIDU_SERVER_URL=${VUE_APP_OPENVIDU_SERVER_URL}
      - VUE_APP_STOPM_SERVER_URL=${VUE_APP_STOPM_SERVER_URL}
